version: "3.8"
services:
  api:
    build: ./devcamper-begin
    container_name: api_c
    ports:
      - '5000:5000'
    volumes: 
      - ./api:/server.js
      - ./app/node_modules
  portfolio:
    build: ./portfolio
    container_name: portfolio_c
    ports:
      - '3000:3000'
    volumes:
      - ./portfolio:/app
      - ./app/node_modules
    stdin_open: true
    tty: true